blank_issues_enabled: true # enable black issues
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/datamol-io/molfeat/discussions
    about: Ask and answer Molfeat related questions.
  - name: ğŸ’¬ Chat with us on slack
    url: https://m2d2group.slack.com/
    about: Live chat with experts, engineers, and datamol users in the M2D2 slack community.
  - name: ğŸ“– Read the documentation
    url: https://molfeat-docs.datamol.io/
    about: Please consult the documentation before opening any issues!
